version: '3.8'

services:
  fetcher:
    build: .
    command: npm run start:fetcher
    environment:
      - NODE_ENV=production
      - FETCHER_PORT=3001
    env_file: .env
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - medipim-network

  maintainer:
    build: .
    command: npm run start:maintainer
    environment:
      - NODE_ENV=production
      - MAINTAINER_PORT=3002
    env_file: .env
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - medipim-network
    depends_on:
      - fetcher

  orchestrator:
    build: .
    command: npm run start:orchestrator
    environment:
      - NODE_ENV=production
      - ORCHESTRATOR_PORT=3003
    env_file: .env
    ports:
      - "3003:3003"
    restart: unless-stopped
    networks:
      - medipim-network
    depends_on:
      - fetcher
      - maintainer

networks:
  medipim-network:
    driver: bridge