# Maintainer Service Configuration
app = "medipim-maintainer"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  MAINTAINER_PORT = "3002"
  NODE_OPTIONS = "--max-old-space-size=2048"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3002
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false

[metrics]
  port = 9091
  path = "/metrics"

[[vm]]
  memory = "8gb"
  cpu_kind = "performance"
  cpus = 4