# Fetcher Service Configuration
app = "medipim-fetcher"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  FETCHER_PORT = "3001"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3001
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "60s"
    grace_period = "30s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[metrics]
  port = 9091
  path = "/metrics"

[[vm]]
  memory = "4gb"
  cpu_kind = "performance"
  cpus = 2